icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "material-nf"

[[block]]
block = "vpn"
driver = "nordvpn"
interval = 10
format_connected = "VPN: $icon "
format_disconnected = "VPN: $icon "
state_connected = "good"
state_disconnected = "warning"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid$frequency}"

[[block]]
block = "xrandr"
format = " $icon $brightness $resolution "

[[block]]
block = "sound"

[[block]]
block = "music"
format = "{ $combo.str(max_w:20,rot_interval:0.5) $prev $play $next |}"
player = "spotify"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:5) "

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$images "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%x %X') "
